project:
  type: website
  output-dir: docs

website:
  title: "Bryn Nurczyk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - projects.qmd
      - publications.qmd

format:
  html:
    css: styles.css
    toc: true



